name: Exercise 2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest wasmtime
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run:
          python3 -m pytest test_fib.py 
        working-directory: exercise2

  write_to_db: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install postgresql
        run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib
          sudo systemctl start postgresql.service

      - name: Write data to DB
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        run: |
          echo Writing team name and exercise to db
          psql -c "INSERT INTO scoreboard (team, exercise) VALUES ('${GITHUB_REF##*/}',2) ON CONFLICT DO NOTHING;" 